### ISSUE TITLE
Create GitHub actions to test new code before merging 

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/TakeTwo-WebAPI#21]
### Background on the problem the feature will solve/improved user experience
Add GitHub Action to test and build new code pushed to a branch or committed to a pull request. Code that passes all the steps in the GitHub action can be merged in the repository.

### Describe the solution you'd like
A GitHub action runs whenever code is committed to any branch or PR is made to the main branch. 

The action will 
- [ ] install dependencies 
- [ ] build for production 
- [ ] run all tests 
- [ ] linting, we haven't chosen a linter so let's discuss options in the comments

You can look at a reference action in [Legit Info](https://github.com/Call-for-Code-for-Racial-Justice/Legit-Info/blob/main/.github/workflows/pythonapp.yml), another Call for Code for Racial Justice project.

### Tasks
- [ ] Ensure install, build and lint steps run locally on your system
- [ ] Read more about [GitHub actions](https://docs.github.com/en/actions/learn-github-actions), in the Build and Test section
- [ ] Create GitHub action You can read more [Python build actions here](https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python?langId=py).
- [ ] Commit and push your GitHub action code.
- [ ] Go to the [Actions tab](https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo-WebAPI/actions) to see if it worked.

### Acceptance Criteria 
GitHub action runs for every new code commit and PR.

FYI @upkarlidder

**Comment by NishaGupta08** [comment]
@demilolu Is this issue available to work on? If yes, would like to try my hands.

**Comment by demilolu** [comment]
Hi @NishaGupta08 yes, I think @sadiejay would be interested in learning so if you could share your process with her that'd be great!

**Comment by sadiejay** [comment]
That works for me! I am very interested in learning your process @NishaGupta08
